#!/usr/bin/env python3
"""
redesign.py — Wallet Hunter MainActivity tab redesign
Run from Termux: python3 ~/wallet-hunter/scripts/redesign.py
"""
import sys

PATH = "/data/data/com.termux/files/home/wallet-hunter/app/src/main/java/com/hunter/btc/MainActivity.kt"

src = open(PATH).read()
orig_len = len(src)

# ══ 1. Chart colors amber→lime ══
src = src.replace(
    "color = 0xFFF59E0B.toInt(); strokeWidth = 2f; style = Paint.Style.STROKE",
    "color = 0xFFA8FF00.toInt(); strokeWidth = 2f; style = Paint.Style.STROKE")
src = src.replace(
    "private val paintDot = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = 0xFFF59E0B.toInt() }",
    "private val paintDot = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = 0xFFA8FF00.toInt() }")
src = src.replace(
    "shader=LinearGradient(0f,0f,0f,h,0x40F59E0B,0x00F59E0B,Shader.TileMode.CLAMP)",
    "shader=LinearGradient(0f,0f,0f,h,0x40A8FF00,0x00A8FF00,Shader.TileMode.CLAMP)")
src = src.replace(
    "color = 0xFF64748B.toInt(); textSize = 18f; typeface = Typeface.MONOSPACE",
    "color = 0xFF556050.toInt(); textSize = 18f; typeface = Typeface.MONOSPACE")
print("1. chart colors OK")

# ══ 2. Find buildUI boundaries ══
START = "    private fun buildUI() {"
END   = "\n    private fun showWalletDialog()"
si = src.find(START)
ei = src.find(END)
if si == -1 or ei == -1:
    print(f"ERROR markers not found: si={si} ei={ei}"); sys.exit(1)
print(f"2. buildUI found: chars {si}..{ei} ({ei-si} chars)")

# ══ 3. New buildUI ══
NEW = (
    "\n"
    "    private var tabPages = listOf<android.view.View>()\n"
    "    private var tabBtns  = listOf<android.widget.TextView>()\n"
    "    private var runStripe: View? = null\n"
    "\n"
    "    private fun goTab(idx: Int) {\n"
    "        tabPages.forEachIndexed { i, v -> v.visibility = if(i==idx) android.view.View.VISIBLE else android.view.View.GONE }\n"
    "        tabBtns.forEachIndexed  { i, b -> b.setTextColor(if(i==idx) AMBER else TXT_MUTED) }\n"
    "        runStripe?.setBackgroundColor(if(HunterEngine.isRunning()) AMBER else BORDER_C)\n"
    "    }\n"
    "\n"
    "    private fun buildUI() {\n"
    "        val prefs = getSharedPreferences(\"hunter\", MODE_PRIVATE)\n"
    "        val root  = android.widget.FrameLayout(this).apply { setBackgroundColor(BG_DEEP) }\n"
    "        val col   = LinearLayout(this).apply {\n"
    "            orientation = LinearLayout.VERTICAL\n"
    "            layoutParams = android.widget.FrameLayout.LayoutParams(\n"
    "                android.widget.FrameLayout.LayoutParams.MATCH_PARENT,\n"
    "                android.widget.FrameLayout.LayoutParams.MATCH_PARENT)\n"
    "        }\n"
    "\n"
    "        /* ══ HEADER ══ */\n"
    "        val header = LinearLayout(this).apply {\n"
    "            orientation = LinearLayout.HORIZONTAL; setBackgroundColor(BG_PANEL)\n"
    "            setPadding(dp(16),dp(11),dp(16),dp(10)); gravity = Gravity.CENTER_VERTICAL\n"
    "            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(54))\n"
    "        }\n"
    "        val mark = TextView(this).apply {\n"
    "            text = \"\u20bf\"; textSize = 14f; setTextColor(android.graphics.Color.BLACK)\n"
    "            typeface = Typeface.create(\"sans-serif-black\", Typeface.BOLD); gravity = Gravity.CENTER\n"
    "            background = GradientDrawable().apply { shape = GradientDrawable.RECTANGLE; setColor(AMBER); cornerRadius = dp(8).toFloat() }\n"
    "            layoutParams = LinearLayout.LayoutParams(dp(30),dp(30)).apply { marginEnd = dp(9) }\n"
    "        }\n"
    "        val brandCol = LinearLayout(this).apply {\n"
    "            orientation = LinearLayout.VERTICAL\n"
    "            layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f)\n"
    "        }\n"
    "        brandCol.addView(TextView(this).apply {\n"
    "            text = s.title; textSize = 14f; setTextColor(TXT_PRI)\n"
    "            typeface = Typeface.create(\"sans-serif-black\", Typeface.BOLD)\n"
    "        })\n"
    "        brandCol.addView(TextView(this).apply {\n"
    "            text = \"libsecp256k1 \u00b7 arm64\"; textSize = 9f; setTextColor(TXT_MUTED)\n"
    "            typeface = Typeface.create(\"monospace\", Typeface.NORMAL)\n"
    "        })\n"
    "        val hRight = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL }\n"
    "        val sysCol = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; gravity = android.view.Gravity.END; setPadding(0,0,dp(7),0) }\n"
    "        tvRam  = TextView(this).apply { text=\"RAM --\"; textSize=9f; setTextColor(TXT_MUTED); typeface=Typeface.create(\"monospace\",Typeface.NORMAL); gravity=android.view.Gravity.END }\n"
    "        tvTemp = TextView(this).apply { text=\"--\u00b0C\"; textSize=10f; setTextColor(AMBER); typeface=Typeface.create(\"monospace\",Typeface.BOLD); gravity=android.view.Gravity.END }\n"
    "        sysCol.addView(tvRam); sysCol.addView(tvTemp)\n"
    "        val btnLang = Button(this).apply {\n"
    "            text = prefs.getString(\"lang\",\"EN\") ?: \"EN\"; textSize=9f; setTextColor(TXT_MUTED)\n"
    "            typeface=Typeface.create(\"monospace\",Typeface.NORMAL)\n"
    "            background=GradientDrawable().apply{setColor(BG_CARD);setStroke(1,BORDER_C);cornerRadius=dp(3).toFloat()}\n"
    "            setPadding(dp(8),dp(3),dp(8),dp(3))\n"
    "            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(26)).apply{marginEnd=dp(6)}\n"
    "            setOnClickListener {\n"
    "                val langKeys=Strings.ALL.keys.toList()\n"
    "                val langNames=mapOf(\"ES\" to \"Espanol\",\"EN\" to \"English\",\"JA\" to \"Japanese\",\"KO\" to \"Korean\",\"DE\" to \"Deutsch\",\"FR\" to \"Francais\",\"RU\" to \"Russian\",\"PT\" to \"Portugues\")\n"
    "                val items=langKeys.map{\"${langNames[it]?:it} ($it)\"}.toTypedArray()\n"
    "                AlertDialog.Builder(this@MainActivity).setTitle(s.language).setItems(items){_,pos->val k=langKeys[pos];applyLang(k);text=k}.show()\n"
    "            }\n"
    "        }\n"
    "        tvLangLbl = TextView(this).apply { text=\"\" }\n"
    "        btnSwitch = Button(this).apply {\n"
    "            text=\"\u229e Wallet\"; textSize=9f; setTextColor(AMBER)\n"
    "            typeface=Typeface.create(\"monospace\",Typeface.BOLD)\n"
    "            background=GradientDrawable().apply{setColor(0x1AA8FF00);setStroke(1,0x33A8FF00);cornerRadius=dp(7).toFloat()}\n"
    "            setPadding(dp(11),dp(6),dp(11),dp(6))\n"
    "            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(32))\n"
    "            setOnClickListener{startActivity(Intent(this@MainActivity,WalletActivity::class.java))}\n"
    "        }\n"
    "        hRight.addView(sysCol); hRight.addView(btnLang); hRight.addView(btnSwitch)\n"
    "        header.addView(mark); header.addView(brandCol); header.addView(hRight)\n"
    "        col.addView(header)\n"
    "        val stripe = View(this).apply { setBackgroundColor(BORDER_C); layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(2)) }\n"
    "        runStripe = stripe; col.addView(stripe)\n"
    "\n"
    "        /* ══ CONTENT FRAME ══ */\n"
    "        val cf = android.widget.FrameLayout(this).apply {\n"
    "            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f)\n"
    "        }\n"
    "        fun cardBg() = GradientDrawable().apply{setColor(BG_PANEL);setStroke(1,BORDER_C);cornerRadius=dp(10).toFloat()}\n"
    "        fun secLbl(t:String) = TextView(this).apply{text=t.uppercase();textSize=9f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.16f;setPadding(0,0,0,dp(10))}\n"
    "\n"
    "        /* ╔═════════════════╗\n"
    "           ║  TAB 0 — SCAN  ║\n"
    "           ╚═════════════════╝ */\n"
    "        val scanScroll = android.widget.ScrollView(this).apply {\n"
    "            setBackgroundColor(BG_DEEP)\n"
    "            layoutParams=android.widget.FrameLayout.LayoutParams(android.widget.FrameLayout.LayoutParams.MATCH_PARENT,android.widget.FrameLayout.LayoutParams.MATCH_PARENT)\n"
    "        }\n"
    "        val scanPage = LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}\n"
    "\n"
    "        /* Speed hero */\n"
    "        val heroBlock = LinearLayout(this).apply {\n"
    "            orientation=LinearLayout.HORIZONTAL; setBackgroundColor(BG_PANEL)\n"
    "            setPadding(dp(18),dp(20),dp(18),dp(18))\n"
    "            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT)\n"
    "        }\n"
    "        val heroLeft = LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)}\n"
    "        heroLeft.addView(TextView(this).apply{text=\"SPEED\";textSize=9f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.18f;setPadding(0,0,0,dp(4))})\n"
    "        tvWps = TextView(this).apply{text=\"0\";textSize=50f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        heroLeft.addView(tvWps)\n"
    "        heroLeft.addView(TextView(this).apply{text=\"keys / second\";textSize=11f;setTextColor(TXT_SEC);setPadding(0,dp(3),0,0)})\n"
    "        val heroRight = LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=android.view.Gravity.END}\n"
    "        tvCount = TextView(this).apply{text=\"0\";textSize=17f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=android.view.Gravity.END}\n"
    "        tvTime  = TextView(this).apply{text=\"00:00:00\";textSize=17f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=android.view.Gravity.END}\n"
    "        heroRight.addView(tvCount)\n"
    "        heroRight.addView(TextView(this).apply{text=s.scanned.uppercase();textSize=8f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=android.view.Gravity.END;letterSpacing=0.13f;setPadding(0,dp(2),0,dp(12))})\n"
    "        heroRight.addView(tvTime)\n"
    "        heroRight.addView(TextView(this).apply{text=s.elapsed.uppercase();textSize=8f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=android.view.Gravity.END;letterSpacing=0.13f;setPadding(0,dp(2),0,0)})\n"
    "        heroBlock.addView(heroLeft); heroBlock.addView(heroRight)\n"
    "        scanPage.addView(heroBlock)\n"
    "        scanPage.addView(View(this).apply{setBackgroundColor(BORDER_C);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "\n"
    "        /* Quick strip */\n"
    "        val qStrip = LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setBackgroundColor(BG_PANEL);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(58))}\n"
    "        fun qCell(value:String,label:String,color:Int,click:(()->Unit)?=null):Pair<LinearLayout,TextView>{\n"
    "            val tv=TextView(this).apply{text=value;textSize=15f;setTextColor(color);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=Gravity.CENTER}\n"
    "            val lb=TextView(this).apply{text=label;textSize=8f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);gravity=Gravity.CENTER;letterSpacing=0.12f}\n"
    "            val cell=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1f);if(click!=null){setOnClickListener{click()};isClickable=true}}\n"
    "            cell.addView(tv);cell.addView(lb);return Pair(cell,tv)\n"
    "        }\n"
    "        fun vDiv()=View(this).apply{setBackgroundColor(BORDER_C);layoutParams=LinearLayout.LayoutParams(1,LinearLayout.LayoutParams.MATCH_PARENT)}\n"
    "        val csvLbl=if(csvPath.isNotEmpty()&&File(csvPath).exists())File(csvPath).nameWithoutExtension.take(7) else \"No file\"\n"
    "        val(c0,_) =qCell(\"${prefs.getInt(\"threads\",3)+1}\",\"THREADS\",AMBER){goTab(3)}\n"
    "        val(c1,_) =qCell(\"${prefs.getInt(\"cpu\",70)+10}%\",\"CPU\",AppTheme.CYAN){goTab(3)}\n"
    "        val(c2,tvQC)=qCell(csvLbl,\"DATASET\",TXT_MUTED){goTab(3)};tvQuickCsv=tvQC\n"
    "        val(c3,tvQM)=qCell(\"0\",\"MATCHES\",TXT_MUTED);tvQuickMatches=tvQM\n"
    "        qStrip.addView(c0);qStrip.addView(vDiv());qStrip.addView(c1);qStrip.addView(vDiv());qStrip.addView(c2);qStrip.addView(vDiv());qStrip.addView(c3)\n"
    "        scanPage.addView(qStrip)\n"
    "        scanPage.addView(View(this).apply{setBackgroundColor(BORDER_C);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "\n"
    "        /* Big action button */\n"
    "        val coinGreen=GradientDrawable().apply{setColor(AppTheme.AMBER);cornerRadius=dp(12).toFloat()}\n"
    "        val coinRed  =GradientDrawable().apply{setColor(AppTheme.RED);cornerRadius=dp(12).toFloat()}\n"
    "        btnToggle=Button(this).apply{\n"
    "            text=s.start;textSize=15f;setTextColor(android.graphics.Color.BLACK)\n"
    "            typeface=Typeface.create(\"sans-serif-black\",Typeface.BOLD);letterSpacing=0.12f;isAllCaps=true\n"
    "            background=coinGreen\n"
    "            layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(56))\n"
    "            setOnClickListener{doToggle()}\n"
    "        }\n"
    "        btnToggle.tag=arrayOf(coinGreen,coinRed)\n"
    "        val actZone=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(14))}\n"
    "        actZone.addView(btnToggle);scanPage.addView(actZone)\n"
    "\n"
    "        /* Stat cards row */\n"
    "        val statSec=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),0,dp(16),0)}\n"
    "        val statGrid=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(0,0,0,dp(6))}\n"
    "        fun statBox(tv:TextView,lbl:String,last:Boolean=false):LinearLayout{\n"
    "            val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();setPadding(dp(12),dp(13),dp(12),dp(13));layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f).apply{if(!last)marginEnd=dp(6)}}\n"
    "            c.addView(tv);c.addView(TextView(this).apply{text=lbl;textSize=8f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.14f;setPadding(0,dp(5),0,0)});return c\n"
    "        }\n"
    "        tvKps=TextView(this).apply{text=\"0\";textSize=22f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val tvSc2=TextView(this).apply{text=\"0\";textSize=18f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val tvTm2=TextView(this).apply{text=\"00:00:00\";textSize=14f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        statGrid.addView(statBox(tvKps,\"KEYS/SEC\"));statGrid.addView(statBox(tvSc2,\"SCANNED\"));statGrid.addView(statBox(tvTm2,\"ELAPSED\",true))\n"
    "        statSec.addView(statGrid)\n"
    "\n"
    "        /* Matches banner */\n"
    "        val matchCard=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;background=cardBg();gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),dp(13),dp(16),dp(13));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(6)}}\n"
    "        val mLeft=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)}\n"
    "        tvMatches=TextView(this).apply{text=\"0\";textSize=28f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        mLeft.addView(TextView(this).apply{text=s.matches.uppercase();textSize=8f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.14f;setPadding(0,0,0,dp(5))})\n"
    "        mLeft.addView(tvMatches);matchCard.addView(mLeft)\n"
    "        matchCard.addView(TextView(this).apply{text=\"~\";textSize=20f;setTextColor(AMBER);typeface=Typeface.MONOSPACE;alpha=0.35f})\n"
    "        statSec.addView(matchCard)\n"
    "\n"
    "        /* Sparkline */\n"
    "        val sparkCard=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();setPadding(dp(14),dp(12),dp(14),dp(12));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(6)}}\n"
    "        sparkCard.addView(TextView(this).apply{text=\"SPEED HISTORY\";textSize=9f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.14f;setPadding(0,0,0,dp(10))})\n"
    "        chartView=SpeedChartView(this).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(52))}\n"
    "        sparkCard.addView(chartView);statSec.addView(sparkCard);scanPage.addView(statSec)\n"
    "\n"
    "        /* Live feed */\n"
    "        val feedSec=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),0,dp(16),0)}\n"
    "        val feedCard=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();clipToOutline=true}\n"
    "        val feedHdr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(9),dp(14),dp(9));setBackgroundColor(0x2D000000)}\n"
    "        feedHdr.addView(View(this).apply{background=GradientDrawable().apply{shape=GradientDrawable.OVAL;setColor(AMBER)};layoutParams=LinearLayout.LayoutParams(dp(6),dp(6)).apply{marginEnd=dp(6)}})\n"
    "        feedHdr.addView(TextView(this).apply{text=\"STREAMING\";textSize=9f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.1f;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)})\n"
    "        feedHdr.addView(TextView(this).apply{text=\"last 3\";textSize=9f;setTextColor(TXT_MUTED)})\n"
    "        feedCard.addView(feedHdr)\n"
    "        tvAddrFeed=TextView(this).apply{text=s.waitingStart;setTextColor(TXT_SEC);textSize=10f;typeface=Typeface.MONOSPACE;setPadding(dp(14),dp(10),dp(14),dp(12));setLineSpacing(0f,1.5f)}\n"
    "        feedCard.addView(tvAddrFeed);feedSec.addView(feedCard)\n"
    "        tvMatchList=TextView(this).apply{text=s.noMatch;setTextColor(TXT_MUTED);textSize=11f;typeface=Typeface.MONOSPACE;background=cardBg();setPadding(dp(14),dp(12),dp(14),dp(12));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{topMargin=dp(6)}}\n"
    "        feedSec.addView(tvMatchList);scanPage.addView(feedSec)\n"
    "        tvStatus=TextView(this).apply{visibility=android.view.View.GONE;text=\"\"}\n"
    "        tvFooter=TextView(this).apply{visibility=android.view.View.GONE;text=\"\"}\n"
    "        scanPage.addView(tvStatus);scanPage.addView(tvFooter)\n"
    "        scanPage.addView(View(this).apply{layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(20))})\n"
    "        /* Tag: [tvKps, tvSc2, tvTm2] for updater sync */\n"
    "        tvWps.tag=arrayOf<Any>(tvKps,tvSc2,tvTm2)\n"
    "        scanScroll.addView(scanPage);cf.addView(scanScroll)\n"
    "\n"
    "        /* ╔═════════════════╗\n"
    "           ║  TAB 1 — LIVE  ║\n"
    "           ╚═════════════════╝ */\n"
    "        val liveScroll=android.widget.ScrollView(this).apply{setBackgroundColor(BG_DEEP);visibility=android.view.View.GONE;layoutParams=android.widget.FrameLayout.LayoutParams(android.widget.FrameLayout.LayoutParams.MATCH_PARENT,android.widget.FrameLayout.LayoutParams.MATCH_PARENT)}\n"
    "        val livePage=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}\n"
    "        val lsHdr=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(BG_PANEL);setPadding(dp(16),dp(16),dp(16),dp(14))}\n"
    "        lsHdr.addView(TextView(this).apply{text=\"SPEED HISTORY\";textSize=10f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.14f;setPadding(0,0,0,dp(12))})\n"
    "        lsHdr.addView(TextView(this).apply{text=\"See Scan tab for chart\";textSize=10f;setTextColor(TXT_MUTED);typeface=Typeface.MONOSPACE})\n"
    "        livePage.addView(lsHdr)\n"
    "        livePage.addView(View(this).apply{setBackgroundColor(BORDER_C);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "        val lfSec=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(20))}\n"
    "        val lfCard=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();clipToOutline=true}\n"
    "        val lfHdr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(9),dp(14),dp(9));setBackgroundColor(0x2D000000)}\n"
    "        lfHdr.addView(View(this).apply{background=GradientDrawable().apply{shape=GradientDrawable.OVAL;setColor(AMBER)};layoutParams=LinearLayout.LayoutParams(dp(6),dp(6)).apply{marginEnd=dp(6)}})\n"
    "        lfHdr.addView(TextView(this).apply{text=\"STREAMING\";textSize=9f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.1f})\n"
    "        lfCard.addView(lfHdr)\n"
    "        lfCard.addView(TextView(this).apply{text=s.waitingStart;setTextColor(TXT_SEC);textSize=10f;typeface=Typeface.MONOSPACE;setPadding(dp(14),dp(10),dp(14),dp(12))})\n"
    "        lfSec.addView(lfCard)\n"
    "        lfSec.addView(TextView(this).apply{text=s.noMatch;setTextColor(TXT_MUTED);textSize=11f;typeface=Typeface.MONOSPACE;background=cardBg();setPadding(dp(14),dp(12),dp(14),dp(12));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{topMargin=dp(6)}})\n"
    "        livePage.addView(lfSec)\n"
    "        tvLiveSec=LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        liveScroll.addView(livePage);cf.addView(liveScroll)\n"
    "\n"
    "        /* ╔══════════════════╗\n"
    "           ║  TAB 2 — STATS  ║\n"
    "           ╚══════════════════╝ */\n"
    "        val statsScroll=android.widget.ScrollView(this).apply{setBackgroundColor(BG_DEEP);visibility=android.view.View.GONE;layoutParams=android.widget.FrameLayout.LayoutParams(android.widget.FrameLayout.LayoutParams.MATCH_PARENT,android.widget.FrameLayout.LayoutParams.MATCH_PARENT)}\n"
    "        val statsPage=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL}\n"
    "        val sHero=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(BG_PANEL);setPadding(dp(20),dp(24),dp(20),dp(20));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT)}\n"
    "        fun heroItem(tv:TextView,lbl:String):LinearLayout{val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)};c.addView(tv);c.addView(TextView(this).apply{text=lbl;textSize=9f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.14f;setPadding(0,dp(4),0,0)});return c}\n"
    "        val sg1=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT)}\n"
    "        val sg2=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{topMargin=dp(16)}}\n"
    "        val sKps=TextView(this).apply{text=\"0\";textSize=24f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val sSc =TextView(this).apply{text=\"0\";textSize=24f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val sEl =TextView(this).apply{text=\"00:00:00\";textSize=24f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val sMt =TextView(this).apply{text=\"0\";textSize=24f;setTextColor(TXT_MUTED);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        sg1.addView(heroItem(sKps,\"KEYS/SEC\"));sg1.addView(heroItem(sSc,\"SCANNED\"))\n"
    "        sg2.addView(heroItem(sEl,\"ELAPSED\"));sg2.addView(heroItem(sMt,\"MATCHES\"))\n"
    "        sHero.addView(sg1);sHero.addView(sg2)\n"
    "        statsPage.addView(sHero)\n"
    "        statsPage.addView(View(this).apply{setBackgroundColor(BORDER_C);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "        val statsBody=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(20))}\n"
    "        statsBody.addView(secLbl(s.statsSection))\n"
    "        val sessCard=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();clipToOutline=true;layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(8)}}\n"
    "        fun sessRow(key:String,tv:TextView){val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),dp(11),dp(16),dp(11))};r.addView(TextView(this).apply{text=key;textSize=11f;setTextColor(TXT_SEC);layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)});r.addView(tv);sessCard.addView(r);sessCard.addView(View(this).apply{setBackgroundColor(0x08FFFFFF);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})}\n"
    "        val sModeV=TextView(this).apply{text=if(puzzleMode)\"PUZZLE\" else \"SEED SCAN\";textSize=11f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        val sThrV =TextView(this).apply{text=\"${prefs.getInt(\"threads\",3)+1}\";textSize=11f;setTextColor(TXT_PRI)}\n"
    "        val sCpuV =TextView(this).apply{text=\"${prefs.getInt(\"cpu\",70)+10}%\";textSize=11f;setTextColor(TXT_PRI)}\n"
    "        val sKeyV =TextView(this).apply{text=\"0\";textSize=11f;setTextColor(TXT_PRI)}\n"
    "        val sDurV =TextView(this).apply{text=\"00:00:00\";textSize=11f;setTextColor(TXT_PRI)}\n"
    "        val sMatV =TextView(this).apply{text=\"0\";textSize=11f;setTextColor(AppTheme.GREEN);typeface=Typeface.create(\"monospace\",Typeface.BOLD)}\n"
    "        sessRow(\"Mode\",sModeV);sessRow(\"Threads\",sThrV);sessRow(\"CPU Limit\",sCpuV)\n"
    "        sessRow(\"Total Keys\",sKeyV);sessRow(\"Duration\",sDurV);sessRow(\"Matches\",sMatV)\n"
    "        statsBody.addView(sessCard)\n"
    "        val statsAct=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL}\n"
    "        statsAct.addView(Button(this).apply{text=\"View Stats\";textSize=11f;setTextColor(android.graphics.Color.BLACK);typeface=Typeface.create(\"sans-serif-black\",Typeface.BOLD);background=GradientDrawable().apply{setColor(AMBER);cornerRadius=dp(10).toFloat()};layoutParams=LinearLayout.LayoutParams(0,dp(44),1f).apply{marginEnd=dp(8)};setOnClickListener{startActivity(Intent(this@MainActivity,StatsActivity::class.java))}})\n"
    "        statsAct.addView(Button(this).apply{text=\"Export Log\";textSize=11f;setTextColor(TXT_PRI);typeface=Typeface.create(\"sans-serif-black\",Typeface.BOLD);background=GradientDrawable().apply{setColor(BG_PANEL);setStroke(1,BORDER_C);cornerRadius=dp(10).toFloat()};layoutParams=LinearLayout.LayoutParams(0,dp(44),1f);setOnClickListener{exportLog()}})\n"
    "        statsBody.addView(statsAct);statsPage.addView(statsBody)\n"
    "        /* extend tag for stats sync: [tvKps,tvSc2,tvTm2, sKps,sSc,sEl,sMt, sKeyV,sDurV,sMatV] */\n"
    "        tvWps.tag=arrayOf<Any>(tvKps,tvSc2,tvTm2,sKps,sSc,sEl,sMt,sKeyV,sDurV,sMatV)\n"
    "        tvStatsSec=LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        tvMatchSec=LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        tvLogSec  =LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        statsScroll.addView(statsPage);cf.addView(statsScroll)\n"
    "\n"
    "        /* ╔═══════════════════╗\n"
    "           ║  TAB 3 — CONFIG  ║\n"
    "           ╚═══════════════════╝ */\n"
    "        val cfgScroll=android.widget.ScrollView(this).apply{setBackgroundColor(BG_DEEP);visibility=android.view.View.GONE;layoutParams=android.widget.FrameLayout.LayoutParams(android.widget.FrameLayout.LayoutParams.MATCH_PARENT,android.widget.FrameLayout.LayoutParams.MATCH_PARENT)}\n"
    "        val cfgPage=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(14),dp(16),dp(24))}\n"
    "        fun cfgCard()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;background=cardBg();clipToOutline=true;layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(8)}}\n"
    "\n"
    "        /* Dataset */\n"
    "        cfgPage.addView(secLbl(s.csvSection))\n"
    "        val dataCard=cfgCard()\n"
    "        val csvRow=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;clipToOutline=true}\n"
    "        btnCsv=Button(this).apply{text=s.csvBtn;textSize=11f;setTextColor(android.graphics.Color.BLACK);typeface=Typeface.create(\"sans-serif-black\",Typeface.BOLD);background=GradientDrawable().apply{setColor(AMBER)};setPadding(dp(18),0,dp(18),0);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(50));setOnClickListener{pickCsv()}}\n"
    "        val csvInfo=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),0,dp(14),0);layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1f)}\n"
    "        val tvCsvName=TextView(this).apply{text=if(csvPath.isNotEmpty()&&File(csvPath).exists())File(csvPath).name else s.noFile;setTextColor(TXT_MUTED);textSize=10f;typeface=Typeface.MONOSPACE;maxLines=1;ellipsize=android.text.TextUtils.TruncateAt.END;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)}\n"
    "        tvStatus=tvCsvName\n"
    "        if(csvPath.isNotEmpty()&&File(csvPath).exists())csvInfo.addView(TextView(this).apply{text=\"\u25cf\";textSize=8f;setTextColor(AppTheme.GREEN);setPadding(dp(6),0,0,0)})\n"
    "        csvInfo.addView(tvCsvName);csvRow.addView(btnCsv);csvRow.addView(csvInfo);dataCard.addView(csvRow)\n"
    "        csvSecView=dataCard;tvCsvSec=LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        cfgPage.addView(dataCard)\n"
    "\n"
    "        /* Performance sliders */\n"
    "        cfgPage.addView(secLbl(s.configSection))\n"
    "        val perfCard=cfgCard()\n"
    "        fun sliderWrap(tv:TextView,bar:SeekBar):LinearLayout{val w=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(14))};w.addView(tv);w.addView(bar);return w}\n"
    "        tvThreads=TextView(this).apply{setTextColor(TXT_PRI);textSize=12f;setPadding(0,0,0,dp(10))}\n"
    "        sbThreads=SeekBar(this).apply{max=7;progress=prefs.getInt(\"threads\",3);setOnSeekBarChangeListener(mkSbl{updateLabels()})}\n"
    "        tvCpu    =TextView(this).apply{setTextColor(TXT_PRI);textSize=12f;setPadding(0,0,0,dp(10))}\n"
    "        sbCpu    =SeekBar(this).apply{max=90;progress=prefs.getInt(\"cpu\",70);setOnSeekBarChangeListener(mkSbl{updateLabels();if(HunterEngine.isRunning())HunterEngine.setCpuLimit(sbCpu.progress+10)})}\n"
    "        perfCard.addView(sliderWrap(tvThreads,sbThreads))\n"
    "        perfCard.addView(View(this).apply{setBackgroundColor(0x08FFFFFF);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "        perfCard.addView(sliderWrap(tvCpu,sbCpu))\n"
    "        cfgPage.addView(perfCard);updateLabels()\n"
    "\n"
    "        /* Search mode */\n"
    "        cfgPage.addView(secLbl(s.modeSection))\n"
    "        val modeCard=cfgCard()\n"
    "        val modeRow=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(dp(12),dp(12),dp(12),dp(12));gravity=Gravity.CENTER_VERTICAL}\n"
    "        rbBip39 =Button(this).apply{text=s.modeBip39;textSize=11f;setTextColor(AMBER);typeface=Typeface.create(\"monospace\",Typeface.BOLD);background=GradientDrawable().apply{setColor(BG_ELEV);setStroke(1,0x33A8FF00);cornerRadius=dp(8).toFloat()};layoutParams=LinearLayout.LayoutParams(0,dp(40),1f).apply{marginEnd=dp(4)};setPadding(dp(4),0,dp(4),0)}\n"
    "        rbPuzzle=Button(this).apply{text=s.modePuzzle;textSize=11f;setTextColor(TXT_SEC);typeface=Typeface.create(\"monospace\",Typeface.NORMAL);background=GradientDrawable().apply{setColor(BG_CARD);setStroke(1,BORDER_C);cornerRadius=dp(8).toFloat()};layoutParams=LinearLayout.LayoutParams(0,dp(40),1f);setPadding(dp(4),0,dp(4),0)}\n"
    "        modeRow.addView(rbBip39);modeRow.addView(rbPuzzle);modeCard.addView(modeRow)\n"
    "        layoutPuzzle=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;visibility=android.view.View.GONE;setPadding(dp(14),0,dp(14),dp(14))}\n"
    "        val dayOfYear=java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_YEAR)\n"
    "        val defaultIdx=dayOfYear%puzzles.size\n"
    "        layoutPuzzle.addView(TextView(this).apply{text=s.puzzleSelect;textSize=9f;setTextColor(TXT_SEC);setPadding(0,0,0,dp(4))})\n"
    "        puzzleSpinner=Spinner(this).apply{adapter=themedAdapter(puzzles.map{\"#${it.num}  -  ${it.btc}  -  ${it.addr.take(16)}...\"});setSelection(defaultIdx);background=GradientDrawable().apply{setColor(BG_CARD);setStroke(1,BORDER_C);cornerRadius=dp(6).toFloat()}}\n"
    "        layoutPuzzle.addView(puzzleSpinner)\n"
    "        val rangeRow=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setPadding(0,dp(8),0,0)}\n"
    "        fun fld(lbl:String):Pair<LinearLayout,EditText>{val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f).apply{marginEnd=dp(4)}};col.addView(TextView(this).apply{text=lbl;textSize=9f;setTextColor(TXT_SEC);setPadding(0,0,0,dp(2))});val et=EditText(this).apply{setTextColor(TXT_PRI);textSize=10f;typeface=Typeface.MONOSPACE;background=GradientDrawable().apply{setColor(BG_ELEV);setStroke(1,BORDER_C);cornerRadius=dp(6).toFloat()};setPadding(dp(8),dp(6),dp(8),dp(6));inputType=android.text.InputType.TYPE_CLASS_TEXT or android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS};col.addView(et);return Pair(col,et)}\n"
    "        val(cS,eS)=fld(s.rangeStart);etRangeStart=eS;rangeRow.addView(cS)\n"
    "        val(cE,eE)=fld(s.rangeEnd);etRangeEnd=eE;rangeRow.addView(cE)\n"
    "        layoutPuzzle.addView(rangeRow)\n"
    "        layoutPuzzle.addView(TextView(this).apply{text=s.targetAddr;textSize=9f;setTextColor(TXT_SEC);setPadding(0,dp(8),0,dp(2))})\n"
    "        etTarget=EditText(this).apply{setTextColor(AMBER);textSize=10f;typeface=Typeface.MONOSPACE;background=GradientDrawable().apply{setColor(BG_ELEV);setStroke(1,BORDER_C);cornerRadius=dp(6).toFloat()};setPadding(dp(8),dp(6),dp(8),dp(6));inputType=android.text.InputType.TYPE_CLASS_TEXT or android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS}\n"
    "        layoutPuzzle.addView(etTarget)\n"
    "        tvPuzzleStatus=TextView(this).apply{text=\"\";textSize=10f;typeface=Typeface.MONOSPACE;setTextColor(AppTheme.GREEN);background=GradientDrawable().apply{setColor(0x1510D97A);setStroke(1,0x2510D97A);cornerRadius=dp(6).toFloat()};setPadding(dp(10),dp(6),dp(10),dp(6));layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{topMargin=dp(6)}}\n"
    "        layoutPuzzle.addView(tvPuzzleStatus);applyPuzzle(puzzles[defaultIdx])\n"
    "        puzzleSpinner.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{var init=true;override fun onItemSelected(a:AdapterView<*>,v:android.view.View?,pos:Int,id:Long){if(init){init=false;return};applyPuzzle(puzzles[pos])};override fun onNothingSelected(a:AdapterView<*>){}}\n"
    "        modeCard.addView(layoutPuzzle);cfgPage.addView(modeCard)\n"
    "        tvConfigSec=LinearLayout(this).also{it.visibility=android.view.View.GONE}\n"
    "        val modeToggle={isPuzzle:Boolean->\n"
    "            puzzleMode=isPuzzle\n"
    "            layoutPuzzle.visibility=if(isPuzzle)android.view.View.VISIBLE else android.view.View.GONE\n"
    "            HunterEngine.setMode(if(isPuzzle)1 else 0)\n"
    "            if(isPuzzle){rbPuzzle.setTextColor(AMBER);rbPuzzle.background=GradientDrawable().apply{setColor(BG_ELEV);setStroke(1,0x33A8FF00);cornerRadius=dp(8).toFloat()};rbBip39.setTextColor(TXT_SEC);rbBip39.background=GradientDrawable().apply{setColor(BG_CARD);setStroke(1,BORDER_C);cornerRadius=dp(8).toFloat()}}\n"
    "            else{rbBip39.setTextColor(AMBER);rbBip39.background=GradientDrawable().apply{setColor(BG_ELEV);setStroke(1,0x33A8FF00);cornerRadius=dp(8).toFloat()};rbPuzzle.setTextColor(TXT_SEC);rbPuzzle.background=GradientDrawable().apply{setColor(BG_CARD);setStroke(1,BORDER_C);cornerRadius=dp(8).toFloat()}}\n"
    "        }\n"
    "        rbBip39.setOnClickListener{modeToggle(false)};rbPuzzle.setOnClickListener{modeToggle(true)}\n"
    "\n"
    "        /* Wallet + export */\n"
    "        cfgPage.addView(secLbl(\"Wallet\"))\n"
    "        val walletCard=cfgCard()\n"
    "        fun navRow(title:String,sub:String,click:()->Unit):LinearLayout{val r=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),dp(13),dp(16),dp(13));isClickable=true;setOnClickListener{click()}};val lc=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)};lc.addView(TextView(this).apply{text=title;textSize=13f;setTextColor(TXT_PRI)});lc.addView(TextView(this).apply{text=sub;textSize=10f;setTextColor(TXT_SEC);typeface=Typeface.MONOSPACE;setPadding(0,dp(2),0,0)});r.addView(lc);r.addView(TextView(this).apply{text=\"\u203a\";textSize=18f;setTextColor(TXT_MUTED)});return r}\n"
    "        walletCard.addView(navRow(\"Open Wallet\",\"View balances & addresses\"){startActivity(Intent(this@MainActivity,WalletActivity::class.java))})\n"
    "        walletCard.addView(View(this).apply{setBackgroundColor(0x08FFFFFF);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,1)})\n"
    "        walletCard.addView(navRow(\"Export Log\",\"Save matches to file\"){exportLog()})\n"
    "        cfgPage.addView(walletCard)\n"
    "\n"
    "        /* Address filter */\n"
    "        cfgPage.addView(secLbl(\"Addr. filter\"))\n"
    "        cfgPage.addView(buildFilterRow().apply{background=cardBg();layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(8)}})\n"
    "\n"
    "        /* System log */\n"
    "        cfgPage.addView(secLbl(s.logSection))\n"
    "        val logCard=cfgCard()\n"
    "        val logHdr=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(9),dp(14),dp(9));setBackgroundColor(0x2D000000)}\n"
    "        logHdr.addView(TextView(this).apply{text=\"System Events\";textSize=9f;setTextColor(TXT_PRI);typeface=Typeface.create(\"monospace\",Typeface.BOLD);layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f)})\n"
    "        logHdr.addView(TextView(this).apply{text=\"last session\";textSize=9f;setTextColor(TXT_MUTED)})\n"
    "        logCard.addView(logHdr)\n"
    "        tvLog=TextView(this).apply{text=\"\";setTextColor(TXT_SEC);textSize=9f;typeface=Typeface.MONOSPACE;setPadding(dp(14),dp(8),dp(14),dp(12));setLineSpacing(0f,1.3f);maxLines=15}\n"
    "        logCard.addView(tvLog);cfgPage.addView(logCard)\n"
    "        cfgScroll.addView(cfgPage);cf.addView(cfgScroll)\n"
    "        col.addView(cf)\n"
    "\n"
    "        /* ══ TABBAR ══ */\n"
    "        val tabBar=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;setBackgroundColor(BG_PANEL);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(62))}\n"
    "        fun tabBtn(ico:String,lbl:String):android.widget.TextView=TextView(this).apply{\n"
    "            text=\"$ico\\n$lbl\";textSize=9f;setTextColor(TXT_MUTED)\n"
    "            typeface=Typeface.create(\"monospace\",Typeface.BOLD);letterSpacing=0.1f\n"
    "            gravity=Gravity.CENTER;isAllCaps=true\n"
    "            layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1f)\n"
    "        }\n"
    "        val tb0=tabBtn(\"\u2299\",\"Scan\");val tb1=tabBtn(\"\u27f3\",\"Live\");val tb2=tabBtn(\"\u25c8\",\"Stats\");val tb3=tabBtn(\"\u2699\",\"Config\")\n"
    "        listOf(tb0,tb1,tb2,tb3).forEach{tabBar.addView(it)}\n"
    "        col.addView(tabBar);root.addView(col);setContentView(root)\n"
    "\n"
    "        tabPages=listOf(scanScroll,liveScroll,statsScroll,cfgScroll)\n"
    "        tabBtns =listOf(tb0,tb1,tb2,tb3)\n"
    "        listOf(tb0,tb1,tb2,tb3).forEachIndexed{i,b->b.setOnClickListener{goTab(i)}}\n"
    "        goTab(0)\n"
    "\n"
    "        /* Restore state */\n"
    "        val uiSp=getSharedPreferences(\"ui_state\",MODE_PRIVATE)\n"
    "        if(uiSp.contains(\"puzzleMode\")){\n"
    "            val wasPuzzle=uiSp.getBoolean(\"puzzleMode\",false)\n"
    "            sbThreads.progress=uiSp.getInt(\"threads\",3);sbCpu.progress=uiSp.getInt(\"cpu\",70)\n"
    "            modeToggle(wasPuzzle)\n"
    "            val savedPuzzleIdx=uiSp.getInt(\"puzzleIdx\",0);suppressPuzzleListener=true;puzzleSpinner.setSelection(savedPuzzleIdx)\n"
    "            val rs=uiSp.getString(\"rangeStart\",\"\")?:\"\";val re=uiSp.getString(\"rangeEnd\",\"\")?:\"\";val tg=uiSp.getString(\"target\",\"\")?:\"\"\n"
    "            if(rs.isNotEmpty())etRangeStart.setText(rs);if(re.isNotEmpty())etRangeEnd.setText(re)\n"
    "            if(tg.isNotEmpty()&&::etTarget.isInitialized)etTarget.setText(tg)\n"
    "            val savedWallet=uiSp.getString(\"activeWallet\",\"\")?:\"\"\n"
    "            if(savedWallet.isNotEmpty()){WalletManager.setActiveWallet(this,savedWallet);val wName=WalletManager.listWallets(this).firstOrNull{p->p.first==savedWallet}?.second?:\"Wallet\";btnSwitch.text=wName.take(10)}\n"
    "            val wasRunning=uiSp.getBoolean(\"isRunning\",false)\n"
    "            if(wasRunning){btnToggle.text=s.stop;btnToggle.background=coinRed;btnToggle.setTextColor(android.graphics.Color.WHITE)}else{btnToggle.text=s.start;btnToggle.background=coinGreen;btnToggle.setTextColor(android.graphics.Color.BLACK)}\n"
    "            val cPts=uiSp.getString(\"chartPts\",\"\")?:\"\";if(cPts.isNotEmpty())cPts.split(\",\").mapNotNull{it.toFloatOrNull()}.forEach{chartView.addPoint(it)}\n"
    "            val sMatch=uiSp.getString(\"matchText\",\"\")?:\"\";if(sMatch.isNotEmpty()&&sMatch!=s.noMatch){tvMatchList.text=sMatch;tvMatchList.setTextColor(AMBER)}\n"
    "            val sFeed=uiSp.getString(\"addrFeed\",\"\")?:\"\";if(sFeed.isNotEmpty()&&sFeed!=s.waitingStart)tvAddrFeed.text=sFeed\n"
    "            val sPSt=uiSp.getString(\"puzzleStatus\",\"\")?:\"\";val sPCol=uiSp.getInt(\"puzzleStatusColor\",AppTheme.TXT_SEC)\n"
    "            if(sPSt.isNotEmpty()&&sPSt!=\"Checking...\")handler.postDelayed({tvPuzzleStatus.text=sPSt;tvPuzzleStatus.setTextColor(sPCol)},300)\n"
    "            val sLog=uiSp.getString(\"logBuf\",\"\")?:\"\";if(sLog.isNotEmpty()){logBuf.clear();logBuf.append(sLog);tvLog.text=logBuf.toString()}\n"
    "            updateLabels();uiSp.edit().clear().apply()\n"
    "        }\n"
    "    }"
)

src = src[:si] + NEW + src[ei:]
print(f"3. buildUI replaced ({len(NEW)} chars)")

# ══ 4. Update updater to sync all stat views ══
src = src.replace(
    'tvWps.text=if(wps>=1e6)"%.2fM".format(wps/1e6) else if(wps>=1000)"%.1fK".format(wps/1000) else "%.0f".format(wps)',
    'val wpsStr=if(wps>=1e6)"%.2fM".format(wps/1e6) else if(wps>=1000)"%.1fK".format(wps/1000) else "%.0f".format(wps)\n'
    '        tvWps.text=wpsStr\n'
    '        (tvWps.tag as? Array<*>)?.let{t->(t.getOrNull(0) as? TextView)?.also{it.text=wpsStr;it.setTextColor(if(running)AMBER else TXT_MUTED)};(t.getOrNull(3) as? TextView)?.also{it.text=wpsStr;it.setTextColor(if(running)AMBER else TXT_MUTED)}}'
)
src = src.replace(
    'if(running) chartView.addPoint(wps.toFloat())\n        tvWps.setTextColor(if(running)AMBER else TXT_MUTED)',
    'if(running) chartView.addPoint(wps.toFloat())'
)
src = src.replace(
    'val count=HunterEngine.getCount(); tvCount.text=if(count>=1_000_000)"%.2fM".format(count/1e6) else if(count>=1000)"%.1fK".format(count/1000.0) else "$count"',
    'val count=HunterEngine.getCount(); val cStr=if(count>=1_000_000)"%.2fM".format(count/1e6) else if(count>=1000)"%.1fK".format(count/1000.0) else "$count"\n'
    '        tvCount.text=cStr\n'
    '        (tvWps.tag as? Array<*>)?.let{t->(t.getOrNull(1) as? TextView)?.text=cStr;(t.getOrNull(4) as? TextView)?.text=cStr}'
)
src = src.replace(
    'val e=HunterEngine.getElapsed(); tvTime.text="%02d:%02d:%02d".format(e/3600,(e%3600)/60,e%60)',
    'val e=HunterEngine.getElapsed(); val eStr="%02d:%02d:%02d".format(e/3600,(e%3600)/60,e%60)\n'
    '        tvTime.text=eStr\n'
    '        (tvWps.tag as? Array<*>)?.let{t->(t.getOrNull(2) as? TextView)?.text=eStr;(t.getOrNull(5) as? TextView)?.text=eStr}'
)
src = src.replace(
    'val found=HunterEngine.getFound(); tvMatches.text="$found"; tvMatches.setTextColor(if(found>0)YELLOW else TXT_MUTED)',
    'val found=HunterEngine.getFound(); tvMatches.text="$found"; tvMatches.setTextColor(if(found>0)AMBER else TXT_MUTED)\n'
    '        tvQuickMatches?.text="$found"; tvQuickMatches?.setTextColor(if(found>0)AMBER else TXT_MUTED)\n'
    '        (tvWps.tag as? Array<*>)?.let{t->(t.getOrNull(6) as? TextView)?.also{it.text="$found";it.setTextColor(if(found>0)AMBER else TXT_MUTED)}}'
)
print("4. updater synced OK")

# ══ 5. Write ══
out = src.encode("utf-8")
open(PATH,"wb").write(out)
bad = [i for i,b in enumerate(out) if b > 127]
print(f"5. non-ASCII bytes: {'CLEAN' if not bad else str(bad[:5])}")
print(f"   orig={orig_len}  new={len(src)}  delta={len(src)-orig_len:+d}")
print("ALL DONE — run: cd ~/wallet-hunter && git add -A && git commit -m 'redesign: tabs' && git push")
